name: maps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter:
  geolocator:
  flutter_bloc:
  material_floating_search_bar:
  get_it:
  equatable:
  dio:
  uuid:
  dartz:
  flutter_polyline_points:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true




